### PR TITLE
update decidim to last commit of 0.18-stable branch

### PR DESCRIPTION
**Pull request by isaacmg410**
https://github.com/decidim/decidim/pull/5362 has been merged and as this organization needs the changes this is the upgrade.

### CODE REVIEW

**Comment by tramuntanal** [comment]
We should wait until this PR is merged: https://github.com/decidim/decidim/pull/5372
and update the Gemfile.lock

**Comment by isaacmg410** [comment]
@tramuntanal updated 0.18-stable last commit. Can you accept please de PR, please?

**Comment by tramuntanal** [comment]
Sorry, there's a new security alert for rubyzip that we must solve. I've done a PR solving it, can you use that branch? https://github.com/decidim/decidim/pull/5393

**Comment by isaacmg410** [comment]
@tramuntanal why? This PR also has rubyzip 1.3.0 version. Check this line.https://github.com/AjuntamentdeSantCugat/decidim-sant_cugat/pull/52/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R662

**Pull request merged**
